/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum BlockMode {
  Independent = 0,
  Linked = 1
}

export declare const enum BlockSize {
  Auto = 0,
  Max64KB = 1,
  Max256KB = 2,
  Max1MB = 3,
  Max4MB = 4,
  Max8MB = 5
}

export declare function compress(data: string | Uint8Array, dict?: string | Uint8Array | undefined | null): Promise<Buffer>

export declare function compressFrame(data: string | Uint8Array, options?: FrameInfoOptions | undefined | null): Promise<Buffer>

export declare function compressFrameSync(data: string | Buffer, options?: FrameInfoOptions | undefined | null): Buffer

/**
 * Compress a Web `ReadableStream<Uint8Array>` into a new byte
 * `ReadableStream` of LZ4-frame-compressed chunks.
 */
export declare function compressStream(input: ReadableStream<Uint8Array>, options?: FrameInfoOptions | undefined | null): ReadableStream<Buffer>

export declare function compressSync(data: string | Buffer, dict?: string | Buffer | undefined | null): Buffer

export declare function decompressFrame(data: string | Uint8Array): Promise<Buffer>

export declare function decompressFrameSync(data: string | Buffer): Buffer

/**
 * Decompress a Web `ReadableStream<Uint8Array>` of LZ4-frame-compressed
 * bytes into a new byte `ReadableStream` of decoded chunks. Mirrors
 * `compress_stream`: the blocking worker owns a `FrameDecoder` over a
 * `BlockingRead` channel adapter, and the async forward loop pulls from
 * the JS reader.
 */
export declare function decompressStream(input: ReadableStream<Uint8Array>): ReadableStream<Buffer>

export interface FrameInfoOptions {
  blockSize?: BlockSize
  blockMode?: BlockMode
  blockChecksums?: boolean
  contentChecksum?: boolean
  contentSize?: number
}

export declare function uncompress(data: string | Uint8Array, dict?: string | Uint8Array | undefined | null): Promise<Buffer>

export declare function uncompressSync(data: string | Uint8Array, dict?: string | Uint8Array | undefined | null): Buffer
